### ISSUE TITLE
When loader is in screen, If I press back button,It doesn't work.

### ISSUE THREAD

**Issue by seckinbrke** [vikrantnegi/react-native-animated-loader#2]
`
const RenderLoadingView = () => {
  return (
    <View style={styles.spinnerContainer}>
      <AnimatedLoader
        visible={true}
        overlayColor="rgba(0,0,0,0.75)"
        source={require("./loading3.json")}
        animationStyle={styles.lottie}
        speed={1}
      />
    </View>);
};

const styles = StyleSheet.create({
  lottie: {
    width: 200,
    height: 200
  },
  spinnerContainer: {
    flex: 1,
    marginTop:30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F1F1F1',
    width: Dimensions.get('window').width,
    height: Dimensions.get('window').height,
  },
});
export default RenderLoadingView;
`

/////////////////////////////////////////////////////////////////////////////////////////////////

`
render = () => {
    if (this.state.isVisible)
      return (<RenderLoadingView/>);
    return this.renderSahisPaydasIsletmeEkle();
  }
`

I did a component. When ı call it , i works nicely. But if my operation take long time, I want press back button in android and Back function doesn't work. 

Before this library, I use react-native-spinkit an I did press back button and it worked.
It was like this:

`
  <Spinner
        isVisible={isVisible}
        type={type}
        size={size} />
`
Please Help Me :)

**Comment by vikrantnegi** [comment]
Hey, thanks for using my package,

I'll add this feature in the next release. Hang tight.

Till then you can change the value of `visible` to false when you want to stop the loader or when you are done with the task.

**Comment by seckinbrke** [comment]
Thanks :) Okey, when will you publish next release.?

**Comment by vikrantnegi** [comment]
@seckinbrke 

Hopefully this week. I'll try to make it faster if I find the time. 
Sorry for any inconvenience you have to face.

Let me know if you need any other features to add.

Thanks.

**Comment by seckinbrke** [comment]
For now, its good accept this :D Thank you I am waiting :)

**Comment by seckinbrke** [comment]
Hi ! I am waiting for you, I wanted to remind you :))

**Comment by vikrantnegi** [comment]
@seckinbrke The more I think about it the more I realize that you might not be using the loader right way.

I've never used the back button to stop loader. Can I know where are you using the loader?

**Comment by seckinbrke** [comment]
I use in get data from api. While It is getting data, It seems in screen. But if take a lot of time, sometimes ı want to go back page. So ı use back button. It's situation :)

**Comment by seckinbrke** [comment]
Expecially android Hardware button too important for me.

**Comment by vikrantnegi** [comment]
@seckinbrke Are you using promises to fetch the API then what you can do is that you can call

```js
this.setState({loading: false)}
``

inside the catch statement. So whenever API requests fail the `loading` will be set to `false` and the loader will stop itself.

If you need help I can help you with this. I use this every day and you don't need back button for this.

**Comment by seckinbrke** [comment]
Yes I use promise then it will be false. This is not my problem. Sometimes getting data in promise take long time. In this condition, I wanna back to old page. So ı should use back button. But if promise doesnt finish, loading page dont close. Always stay my screen. This is my problem. I hope , ı describe my problem :)

**Comment by arsalan-arshad** [comment]
you can use my fork repo
https://github.com/arsalan-arshad/react-native-animated-loader

> `
> const RenderLoadingView = () => {
> return (
> 
> <AnimatedLoader
> visible={true}
> overlayColor="rgba(0,0,0,0.75)"
> source={require("./loading3.json")}
> animationStyle={styles.lottie}
> speed={1}
> />
> );
> };
> 
> const styles = StyleSheet.create({
> lottie: {
> width: 200,
> height: 200
> },
> spinnerContainer: {
> flex: 1,
> marginTop:30,
> justifyContent: 'center',
> alignItems: 'center',
> backgroundColor: '#F1F1F1',
> width: Dimensions.get('window').width,
> height: Dimensions.get('window').height,
> },
> });
> export default RenderLoadingView;
> `
> 
> /////////////////////////////////////////////////////////////////////////////////////////////////
> 
> `render = () => { if (this.state.isVisible) return (<RenderLoadingView/>); return this.renderSahisPaydasIsletmeEkle(); }`
> 
> I did a component. When ı call it , i works nicely. But if my operation take long time, I want press back button in android and Back function doesn't work.
> 
> Before this library, I use react-native-spinkit an I did press back button and it worked.
> It was like this:
> 
> `<Spinner isVisible={isVisible} type={type} size={size} />`
> Please Help Me :)

you can use my fork repo
https://github.com/arsalan-arshad/react-native-animated-loader

![Screenshot_20200320-225615](https://user-images.githubusercontent.com/17481154/77192541-8beca280-6afe-11ea-8550-b87376ac1185.png)

**Comment by Vigneshpillai19** [comment]
Inside node_modules folder open the "index.js" file from "react-native-animated-loader/src" and edit the following line of code
Inside the render method:
<Modal
    ......
    onRequestClose={() => { /* write your logic here */  }}  //This function is called when back button is clicked
 />

If you want to access navigation inside this file do the following changes:

import { withNavigation } from 'react-navigation';
class AnimatedLoader extends React.PureComment {
    .....
    ....
    render() {
        return(
            <Modal
               ........
               ........
               onRequestClose={() => { this.props.navigation.goBack(null) } }
             />
        )
    }
}
// After completion of code export the component with 'withNavigation' like
export default withNavigation(AnimatedLoader);
